KA15/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('reports/', include('report_list.urls')),
    path('form/', include('report_form.urls')),
    path('testimony/', include('testimony.urls')),
]

testimony/urls.py
from django.urls import path
from . import views

app_name = 'testimony'

urlpatterns = [
	path('', views.testimony, name='testimony'),
	path('add_testimony/', views.add_testimony, name="add_testimony"),
]

testimony/models.py
from django.db import models

class Testimony(models.Model):
	username = models.CharField(max_length = 20)
	title = models.CharField(max_length = 50)
	content = models.TextField()

	def __str__(self):
		return f"{self.title}"

testimony/forms.py
from django import forms

class TestimonyForm(forms.Form):
	username_attrs = {
		'placeholder': 'Username',
		'class': 'form-control',
	}

	title_attrs = {
		'placeholder': 'Title',
		'class': 'form-control',
	}

	content_attrs = {
		'placeholder': 'Write your testimony here...',
		'class': 'form-control',
		'rows': 5,
	}

	username = forms.CharField(label='', max_length = 20, widget = forms.TextInput(attrs = username_attrs))
	title = forms.CharField(label='', max_length = 50, widget = forms.TextInput(attrs = title_attrs))
	content = forms.CharField(label='', widget = forms.Textarea(attrs = content_attrs))

testimony/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TestimonyForm
from .models import Testimony


def testimony(request):
	form = TestimonyForm()
	testimony = Testimony.objects.all()
	return render(request, 'testimony.html', {'form': form, 'testimony': testimony})

def add_testimony(request):
	if request.method == 'POST':
		form = TestimonyForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			title = form.cleaned_data['title']
			content = form.cleaned_data['content']
			
			testimony = Testimony(username = username, title = title, content = content)
			testimony.save()

	return HttpResponseRedirect(reverse('testimony:testimony'))

testimony/templates/testimony.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/testimony_style.css' %}">
{% endblock %}

{% block title %}
	Testimony
{% endblock %}

{% block body %}
	{% include 'base/navbar.html' %}
	
	<div class="content-div">
		<p class="section-title text-center">TESTIMONY</p>
		<button href="#testimony-form" class="form-group btn-submit" data-toggle="collapse">Testify</button>
		<div class="collapse in" id="testimony-form">
			<form action="{% url 'testimony:add_testimony' %}" method="POST">
				{% csrf_token %}

				<div class="form-row">
					<div class="form-group col-sm-4">
						{{ form.username }}
					</div>
					<div class="form-group col-sm-8">
						{{ form.title }}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-sm-12">
						{{ form.content }}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-sm-12">
						<input class="form-group btn-submit float-right" type="submit" value="Post">
					</div>
				</div>		
			</form>
		</div>

		{% for testimony in testimony reversed %}
		<div class="testimony-div bg-light">
			<div class="d-flex justify-content-start">
				<div class="testimony-detail">
					<p class="testimony-title">{{ testimony.title }}</p>
					<p class="testimony-time">by <span class="testimony-author">{{ testimony.username }}</span></p>
				</div>
			</div>

			<div class="testimony-content">
				{{ testimony.content }}
			</div>
		</div>
		{% endfor %}
	</div>


	{% include 'base/footer.html' %}
{% endblock %}