KA15/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('reports/', include('report_list.urls')),
    path('form/', include('report_form.urls')),
    path('testimony/', include('testimony.urls')),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('add_announcement', views.add_announcement, name="add_announcement"),
]

report_form/urls.py
from django.urls import path
from . import views

app_name = 'report_form'

urlpatterns = [
	path('', views.index, name= 'report_form'),
	path('', views.add_report, name= 'add_report'),
]

report_list/urls.py
from django.urls import path
from . import views

app_name='report_list'

urlpatterns = [
	path('', views.report_list, name= 'report_list'),
	#path('', views.add_report, name= 'add_report_form'),
]

testimony/urls.py
from django.urls import path
from . import views

app_name = 'testimony'

urlpatterns = [
	path('', views.testimony, name='testimony'),
	path('add_testimony/', views.add_testimony, name="add_testimony"),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'base/index.html')

base/templates/base/footer.html
{% load static %}

<footer>
	<div class="container text-center">
		<ul class="list-inline">
			<li class="list-inline-item">
				<img src="{% static 'base/images/instagram.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
			<li class="list-inline-item">
				<img src="{% static 'base/images/twitter.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
			<li class="list-inline-item">
				<img src="{% static 'base/images/facebook.png' %}" class="img-contact">
				<p class="contact-text">pacility.</p>
			</li>
		</ul>

		<span id="footer-divider"></span>
		<p class="copyright">© 2019 pacility. | ALL RIGHTS RESERVED</p>
	</div>
</footer>

base/templates/base/index.html
<!DOCTYPE html>
<html>
	<head>
		<title>KA15 - Project 1</title>
	</head>
	<body>
		<h1>Hello World</h1>
	</body>
</html>

base/templates/base/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<title>{% block title %} {% endblock %} - pacility.</title>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'base/css/base_style.css' %}">
		{% block link %} {% endblock %}
		<link href="https://fonts.googleapis.com/css?family=Raleway:400,500,800" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Rufina:400,700" rel="stylesheet">
<!-- 		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
 		<!-- <link href="https://fonts.googleapis.com/css?family=Strait&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=PT+Serif&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=PT+Sans&display=swap" rel="stylesheet"> -->
		<link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
		
	</head>

	<body>
		{% block body %}

		{% endblock %}
	</body>
</html>

base/templates/base/navbar.html
<nav class="navbar navbar-expand-sm sticky-top navbar-custom">
  	<a class="navbar-brand" href="#">pacility.</a>
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content">
    	<span class="navbar-toggler-icon"></span>
  	</button>
  	<div class="collapse navbar-collapse" id="nav-content">
    	<div class="navbar-nav ml-auto">
      		<a class="nav-item nav-link" href="{% url 'homepage:index' %}">Home</a>
      		<a class="nav-item nav-link" href="{% url 'report_list:report_list' %}">Report</a>
      		<a class="nav-item nav-link" href="{% url 'report_form:report_form' %}">Form</a>
      		<a class="nav-item nav-link" href="{% url 'testimony:testimony' %}">Testimony</a>
    	</div>
  </div>
</nav>