KA15/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('reports/', include('report_list.urls')),
    path('form/', include('report_form.urls')),
    path('testimony/', include('testimony.urls')),
]

report_form/urls.py
from django.urls import path
from . import views

app_name = 'report_form'

urlpatterns = [
	path('', views.index, name= 'report_form'),
	path('', views.add_report, name= 'add_report'),
]

report_form/models.py
from django.db import models

class Report(models.Model):
	form_title = models.CharField(max_length = 20)
	location = models.CharField(max_length = 20)
	time = models.TimeField()
	category = models.CharField(max_length = 20)
	description = models.TextField()

	def is_valid_report(self):
	    form_title_valid = len(self.form_title) > 0 and len(self.form_title) < 21
	    location_valid = len(self.location) > 0 and len(self.location) < 21
	    category_valid = len(self.category) > 0 and len(self.category) < 21
	    description_valid = len(self.description) > 0

	    return form_title_valid and location_valid and category_valid and description_valid

	def __str__(self):
	    return f"{self.time} - {self.form_title}"

report_form/forms.py
from django import forms

class ReportForm(forms.Form):
    form_title_attrs = {
        'placeholder' : 'Title',
        'class' : 'form-control',
    }
    location_attrs = {
        'placeholder' : 'Location',
        'class' : 'form-control',
    }
    time_attrs = {
        'type'  : 'time',
        'placeholder' : 'Time',
        'class' : 'form-control',
    }
    category_attrs = {
        'placeholder' : 'Category',
        'class' : 'form-control',
    }
    description_attrs = {
        'placeholder' : 'Write your description here...',
        'class' : 'form-control',
    }

    form_title = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = form_title_attrs))
    location = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = location_attrs))
    time = forms.TimeField(label= '',required=True, localize=True, widget = forms.TimeInput(attrs = time_attrs))
    category = forms.CharField(label= '', max_length = 50, widget = forms.TextInput(attrs = category_attrs))
    description = forms.CharField(label = '', widget = forms.Textarea(attrs = description_attrs))

report_form/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ReportForm
from .models import Report
from datetime import datetime

def index(request):
	form = ReportForm()
	reports = Report.objects.all()
	return render(request, 'report_form/report_form.html', {'form': form, 'reports': reports})

def add_report(request):
    if(request.method == 'POST'):
        form = ReportForm(request.POST)
        #reports = Report.objects.all()
        if form.is_valid():
            form_title = form.changed_data['form_title']
            location = form.changed_data['location']
            time = form.changed_data['time']
            category = form.changed_data['category']
            description =  form.changed_data['description']

            report = Report(
                form_title = form_title,
                location = location,
                time = time,
                category = category,
                description = description
            )
            report.save()
        return render(request, 'report_form/report_form.html', {'form': form, 'reports': reports})

report_form/templates/report_form/report_form.html
{% extends 'base/layout.html' %}
{% load static %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'report_form/css/form_style.css' %}">
{% endblock %}

{% block title %}
    Form
{% endblock %}

{% block body %}

{% include 'base/navbar.html' %}

<div class="content-div">
    <p class="section-title">REPORT FORM</p>
    <form action="{% url 'report_form:add_report' %}" method="POST" id="report_form-form">
        {% csrf_token %}

        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.form_title }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.location }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.time }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-sm-8">
                {{ form.category }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-12">
                {{ form.description }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-12">
                <input class="form-group btn-submit float-right" type="submit" value="Report">
            </div>
        </div>
    </form>
</div>

{% include 'base/footer.html' %}
{% endblock %}